Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -23,8 +23,8 @@ jobs:
         run: |
           pip install -r requirements.txt
           sudo apt update
-          sudo apt install -y chromium-chromedriver
-          sudo ln -s /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver
-
+          sudo apt install -y chromium-chromedriver || true  # ⚠ Ignore error if already installed
+          which chromedriver || echo "Chromedriver not found!"
+      
       - name: Run Bot
         run: python main.py
